source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AFMActionSheet_Example' do
  pod "AFMActionSheet", :path => "../"
end

target 'AFMActionSheet_Tests' do
  pod "AFMActionSheet", :path => "../"

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end

post_install do |installer|
  target = installer.pods_project.targets.find { |target| target.name == 'AFMActionSheet' }
  debug_config = target.build_configurations.find { |config| config.name == 'Debug' }
  debug_config.build_settings['ENABLE_TESTABILITY'] = 'YES'
end
